# Generated by Django 3.2.12 on 2024-02-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seek', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_cover',
        ),
        migrations.RemoveField(
            model_name='business',
            name='business_logo',
        ),
        migrations.RemoveField(
            model_name='business',
            name='category',
        ),
    ]
